name: stocks-research
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas=1.5.3
  - numpy=1.24.3
  - yfinance>=0.2.28
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.17.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0
  - streamlit>=1.28.0
  - requests>=2.31.0
  - python-dotenv>=1.0.0
  - openpyxl>=3.1.0
  - pip
  - pip:
    - yfinance>=0.2.28 